// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Jovana_Golijanin.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230314130710_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojIndeksa")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Igrac");
                });

            modelBuilder.Entity("Models.Partija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DrugiIgracID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzinaPartije")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PrviIgracID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DrugiIgracID");

                    b.HasIndex("PrviIgracID");

                    b.ToTable("Partija");
                });

            modelBuilder.Entity("Models.Potezi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Kolona")
                        .HasColumnType("int");

                    b.Property<int?>("PartijaID")
                        .HasColumnType("int");

                    b.Property<int>("Vrsta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PartijaID");

                    b.ToTable("Potezi");
                });

            modelBuilder.Entity("Models.Partija", b =>
                {
                    b.HasOne("Models.Igrac", "DrugiIgrac")
                        .WithMany("DrugiIgra")
                        .HasForeignKey("DrugiIgracID");

                    b.HasOne("Models.Igrac", "PrviIgrac")
                        .WithMany("PrviIgra")
                        .HasForeignKey("PrviIgracID");

                    b.Navigation("DrugiIgrac");

                    b.Navigation("PrviIgrac");
                });

            modelBuilder.Entity("Models.Potezi", b =>
                {
                    b.HasOne("Models.Partija", "Partija")
                        .WithMany("Potezi")
                        .HasForeignKey("PartijaID");

                    b.Navigation("Partija");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Navigation("DrugiIgra");

                    b.Navigation("PrviIgra");
                });

            modelBuilder.Entity("Models.Partija", b =>
                {
                    b.Navigation("Potezi");
                });
#pragma warning restore 612, 618
        }
    }
}
