// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Jovana_Golijanin.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230701091427_v5")]
    partial class v5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojIndeksa")
                        .HasColumnType("int");

                    b.Property<int>("BrojNeresenih")
                        .HasColumnType("int");

                    b.Property<int>("BrojPobeda")
                        .HasColumnType("int");

                    b.Property<int>("BrojPoraza")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Igrac");
                });

            modelBuilder.Entity("Models.Partija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DuzinaPartije")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IgracID")
                        .HasColumnType("int");

                    b.Property<string>("PobednikCovek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremeKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IgracID");

                    b.ToTable("Partija");
                });

            modelBuilder.Entity("Models.Partija", b =>
                {
                    b.HasOne("Models.Igrac", "Igrac")
                        .WithMany("ListaPartija")
                        .HasForeignKey("IgracID");

                    b.Navigation("Igrac");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Navigation("ListaPartija");
                });
#pragma warning restore 612, 618
        }
    }
}
